### ISSUE TITLE
Wait for postgresql to accecpt connections before starting httpd

### ISSUE THREAD

**Issue by Schpidi** [EOX-A/ngeo-b#19]
In the provided init.d script in `install/ngeo` httpd should only be started after postgresql is accepting connections to avoid hanging processes.

Note that the error message logged in httpd error log for a hanging process is `ImportError: cannot import name utils` which is not telling the real cause. Restarting httpd usually resolves the issue.

**Comment by Schpidi** [comment]
The `-w` switch of `pg_ctl start -w` would help but apparently the postgresql init.d script is not using pg_ctl to start the server.

**Comment by constantinius** [comment]
For PostgreSQL 9.3+ there is the pg_isready command (https://www.postgresql.org/docs/9.3/static/app-pg-isready.html) which we could use in a busy loop to determine when the DB is ready.

**Comment by Schpidi** [comment]
Great that we're stuck with 8.4 in CentOS 6 :(
